### ISSUE TITLE
Add Github action to push image to Quay.io

### ISSUE THREAD

**Issue by intlabs** [att-comdev/jarvis-connector#1]
A GitHub action should be added to build the jarvis-connector image and push it to quay.io, on every merge, and once per week.

The tag(s) should be: the git short sha, and also 'latest' for each push.

**Comment by DannyMassa** [comment]
I cannot validate without the real credentials, but here is a look at the Quay test repository I was using:


![image](https://user-images.githubusercontent.com/22630192/105403961-04c0fd00-5bef-11eb-9b9e-e75cebac5bae.png)

**Comment by intlabs** [comment]
Completed with https://github.com/att-comdev/jarvis-connector/pull/3
