### ISSUE TITLE
Image should have labels according to the open-containers image spec.

### ISSUE THREAD

**Issue by intlabs** [att-comdev/jarvis-connector#2]
See: https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys

Should be completed as a rapid followup to #1

**Comment by DannyMassa** [comment]
Quay example from test repo: 
![image](https://user-images.githubusercontent.com/22630192/105779213-7b356600-5f33-11eb-984d-0d83756f4f40.png)

**Comment by DannyMassa** [comment]
Was this closed by #8?

EDIT: With #8 reverted, this issue is still open
